# Port wbudowanego serwera Tomcat
server.port=8081

# Konfiguracja po\u00c5\u0082\u00c4\u0085czenia z PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/kosiarkobot_db
spring.datasource.username=postgres
spring.datasource.password=admin

# Hibernate: Automatyczne tworzenie/aktualizowanie tabel na podstawie klas
spring.jpa.hibernate.ddl-auto=update
# Hibernate: Pokazywanie zapyta\u00c5\u0084 SQL w konsoli NetBeans
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true